/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/$portal/index'
import { Route as PortalLayoutRouteImport } from './routes/$portal/_layout'
import { Route as PortalSectionRouteImport } from './routes/$portal/$section'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/$portal/',
  path: '/$portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLayoutRoute = PortalLayoutRouteImport.update({
  id: '/$portal/_layout',
  path: '/$portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSectionRoute = PortalSectionRouteImport.update({
  id: '/$portal/$section',
  path: '/$portal/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/$portal/$section': typeof PortalSectionRoute
  '/$portal': typeof PortalLayoutRoute
  '/$portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/$portal/$section': typeof PortalSectionRoute
  '/$portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/$portal/$section': typeof PortalSectionRoute
  '/$portal/_layout': typeof PortalLayoutRoute
  '/$portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/$portal/$section'
    | '/$portal'
    | '/$portal/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/unauthorized' | '/$portal/$section' | '/$portal'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/unauthorized'
    | '/$portal/$section'
    | '/$portal/_layout'
    | '/$portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  PortalSectionRoute: typeof PortalSectionRoute
  PortalLayoutRoute: typeof PortalLayoutRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$portal/': {
      id: '/$portal/'
      path: '/$portal'
      fullPath: '/$portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$portal/_layout': {
      id: '/$portal/_layout'
      path: '/$portal'
      fullPath: '/$portal'
      preLoaderRoute: typeof PortalLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$portal/$section': {
      id: '/$portal/$section'
      path: '/$portal/$section'
      fullPath: '/$portal/$section'
      preLoaderRoute: typeof PortalSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  PortalSectionRoute: PortalSectionRoute,
  PortalLayoutRoute: PortalLayoutRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
